"""Immutable metadata contracts and pure standards-to-design auditing."""

from ._contract import VERSION, ModelError
from .models import (
    Attribute,
    CatalogSnapshot,
    Column,
    Constraint,
    ConstraintKind,
    Coverage,
    DesignRevision,
    Dialect,
    Document,
    Domain,
    Identifier,
    LogicalName,
    NameOrigin,
    NamingPolicy,
    Reason,
    SourceLocation,
    StandardRevision,
    State,
    Table,
    Term,
    TypeDescriptor,
    Word,
    absent,
    known,
    unknown,
)
from .normalization import (
    NormalizationRegistry,
    normalize_identifier,
    normalize_logical_name,
    normalize_type,
)
from .results import Finding, FindingSet, Verdict
from .rules.implementation import ImplementationCheck, ImplementationReport, audit_implementation
from .rules.standards import AuditCheck, StandardsReport, TermBinding, audit_standards
from .schema import json_schema
from .serialization import (
    dump_document,
    load_document,
    raw_digest,
    semantic_bytes,
    semantic_digest,
    to_dict,
)

__all__ = [
    "ImplementationCheck",
    "ImplementationReport",
    "audit_implementation",
    "AuditCheck",
    "StandardsReport",
    "TermBinding",
    "audit_standards",
    "VERSION",
    "ModelError",
    "Attribute",
    "CatalogSnapshot",
    "Column",
    "Constraint",
    "ConstraintKind",
    "Coverage",
    "DesignRevision",
    "Dialect",
    "Document",
    "Domain",
    "Identifier",
    "LogicalName",
    "NameOrigin",
    "NamingPolicy",
    "Reason",
    "SourceLocation",
    "StandardRevision",
    "State",
    "Table",
    "Term",
    "TypeDescriptor",
    "Word",
    "absent",
    "known",
    "unknown",
    "NormalizationRegistry",
    "normalize_identifier",
    "normalize_logical_name",
    "normalize_type",
    "Finding",
    "FindingSet",
    "Verdict",
    "json_schema",
    "dump_document",
    "load_document",
    "raw_digest",
    "semantic_bytes",
    "semantic_digest",
    "to_dict",
]
