"""Visual smoke tests for Data Docs A4 report output."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from truthound.datadocs import HTMLReportBuilder, ReportTheme, export_to_pdf
from truthound.datadocs.builder import generate_html_report

from .fixtures import PUBLIC_REPORT_THEMES, sample_a4_report_profile


REQUIRE_PDF_SMOKE_ENV = "TRUTHOUND_DATADOCS_REQUIRE_PDF_SMOKE"
REQUIRE_PDF_RENDER_ENV = "TRUTHOUND_DATADOCS_REQUIRE_PDF_RENDER"


def _env_flag_enabled(value: str) -> bool:
    return value.lower() in {"1", "true", "yes", "on"}


def _skip_or_fail_pdf_dependency(message: str, *, require_env: str = REQUIRE_PDF_SMOKE_ENV) -> None:
    if _env_flag_enabled(os.environ.get(require_env, "")):
        pytest.fail(message)
    pytest.skip(message)


def _assert_a4_report_visual_markers(html: str, theme: str) -> None:
    assert "<!DOCTYPE html>" in html
    assert "Truthound A4 Visual Smoke" in html
    assert f'name="{theme}"' in html or f"theme-{theme}" in html or "Generated by Truthound" in html
    assert "@page" in html
    assert "size: A4 portrait" in html
    assert "width: 210mm" in html
    assert "min-height: 297mm" in html
    assert "Malgun Gothic" in html
    assert "맑은 고딕" in html
    assert "border-collapse: collapse" in html
    assert "table-header-group" in html
    assert ".summary-box" in html
    assert ".report-caption" in html
    assert "page-break-inside: avoid" in html
    assert "break-inside: avoid" in html
    assert "Column Summary" in html


def _extract_pdf_text(output_path: Path) -> str | None:
    try:
        from pypdf import PdfReader
    except ImportError:
        try:
            import pdfplumber
        except ImportError:
            return None

        with pdfplumber.open(output_path) as pdf:
            return "\n".join(page.extract_text() or "" for page in pdf.pages)

    reader = PdfReader(str(output_path))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def _assert_pdf_text_smoke(output_path: Path) -> None:
    text = _extract_pdf_text(output_path)
    if text is None:
        _skip_or_fail_pdf_dependency(
            "PDF text extraction smoke requires pypdf or pdfplumber; install one or unset "
            f"{REQUIRE_PDF_SMOKE_ENV}."
        )

    assert text is not None
    assert "Truthound A4 Visual Smoke" in text
    assert "Column Summary" in text or "sample-quality-profile.csv" in text


def _assert_optional_pdf_page_render(output_path: Path, tmp_path: Path) -> None:
    pdftoppm = shutil.which("pdftoppm")
    if pdftoppm is None:
        if _env_flag_enabled(os.environ.get(REQUIRE_PDF_RENDER_ENV, "")):
            pytest.fail(
                "PDF first-page render smoke requires Poppler pdftoppm; install Poppler or unset "
                f"{REQUIRE_PDF_RENDER_ENV}."
            )
        return

    prefix = tmp_path / "truthound-a4-visual-smoke-page"
    subprocess.run(
        [pdftoppm, "-png", "-f", "1", "-singlefile", str(output_path), str(prefix)],
        check=True,
        capture_output=True,
        text=True,
    )
    rendered_page = tmp_path / "truthound-a4-visual-smoke-page.png"
    assert rendered_page.exists()
    assert rendered_page.stat().st_size > 10_000


@pytest.mark.parametrize("theme", PUBLIC_REPORT_THEMES)
def test_public_themes_render_a4_html_visual_smoke(theme: str) -> None:
    html = generate_html_report(
        sample_a4_report_profile(),
        title="Truthound A4 Visual Smoke",
        subtitle=f"{theme} theme regression fixture",
        theme=theme,
    )

    _assert_a4_report_visual_markers(html, theme)


def test_pdf_ready_html_uses_svg_and_a4_report_css() -> None:
    html = HTMLReportBuilder(theme=ReportTheme.LIGHT, _use_svg=True).build_for_pdf(
        sample_a4_report_profile(),
        title="Truthound A4 Visual Smoke",
        subtitle="PDF-ready visual smoke",
    )

    _assert_a4_report_visual_markers(html, "light")
    assert "<svg" in html
    assert "apexcharts" not in html.lower()
    assert "Korean Public/Research PDF Document Styling" in html


def test_pdf_export_visual_smoke_when_weasyprint_is_available(tmp_path) -> None:
    try:
        import weasyprint  # noqa: F401
    except (ImportError, OSError) as error:
        _skip_or_fail_pdf_dependency(f"WeasyPrint is not available in this environment: {error}")

    output_path = tmp_path / "truthound-a4-visual-smoke.pdf"
    try:
        export_to_pdf(
            sample_a4_report_profile(),
            output_path,
            title="Truthound A4 Visual Smoke",
            subtitle="Generated PDF visual smoke",
            theme="light",
        )
    except ImportError as error:
        _skip_or_fail_pdf_dependency(f"PDF system dependencies are not available: {error}")

    pdf_bytes = output_path.read_bytes()
    assert pdf_bytes.startswith(b"%PDF")
    assert len(pdf_bytes) > 5_000
    _assert_pdf_text_smoke(output_path)
    _assert_optional_pdf_page_render(output_path, tmp_path)


def test_pdf_smoke_require_env_turns_missing_dependency_into_failure(monkeypatch) -> None:
    monkeypatch.setenv(REQUIRE_PDF_SMOKE_ENV, "1")

    with pytest.raises(pytest.fail.Exception):
        _skip_or_fail_pdf_dependency("missing dependency")


def test_pdf_render_require_env_turns_missing_poppler_into_failure(monkeypatch, tmp_path) -> None:
    monkeypatch.setenv(REQUIRE_PDF_RENDER_ENV, "1")
    monkeypatch.setattr(shutil, "which", lambda _: None)

    with pytest.raises(pytest.fail.Exception):
        _assert_optional_pdf_page_render(tmp_path / "missing.pdf", tmp_path)


def test_visual_smoke_docs_are_public_and_localized() -> None:
    english = "docs/guides/datadocs/pdf-export.md"
    korean = "docs/locales/ko/guides/datadocs/pdf-export.md"

    english_text = open(english, encoding="utf-8").read()
    korean_text = open(korean, encoding="utf-8").read()

    assert "Visual Smoke Testing" in english_text
    assert "light`, `dark`, and `minimal" in english_text
    assert "WeasyPrint" in english_text
    assert REQUIRE_PDF_SMOKE_ENV in english_text
    assert REQUIRE_PDF_RENDER_ENV in english_text
    assert "Visual Smoke Testing" in korean_text
    assert "`light`, `dark`, `minimal`" in korean_text
    assert "WeasyPrint" in korean_text
    assert REQUIRE_PDF_SMOKE_ENV in korean_text
    assert REQUIRE_PDF_RENDER_ENV in korean_text
